apiVersion: v1
name: syslog-ng
description: Syslog-ng
version: 0.2
appVersion: 3.27.1
maintainers:
  - name: zakkg3
sources:
  - https://github.com/balabit/syslog-ng-docker
keywords:
  - Syslog
  - syslog-ng
  - logrotate
